import json

valid_filters = {
    'Regions':
    {
        'Africa':
        {
            'Subregions':
            {
            'Algeria': {}, 
            'Angola': {}, 
            'Benin': {}, 
            'Botswana': {}, 
            'Burkina Faso': {}, 
            'Burundi': {}, 
            'Cameroon': {}, 
            'Cape Verde (Cabo Verde)': {}, 
            'Central Africa Republic': {}, 
            'Chad': {}, 
            'Democratic Republic of the Congo': {}, 
            'Dijbouti': {}, 
            'Egypt': {}, 
            'Ethiopia': {}, 
            'Ghana': {}, 
            "Ivory Cost(Côte d'Ivoire)": {}, 
            'Kenya': {}, 
            'Lesotho': {}, 
            'Liberia': {}, 
            'Libya': {}, 
            'Madagascar': {}, 
            'Malawi': {}, 
            'Mauritius': {}, 
            'Mozambique': {}, 
            'Namibia': {}, 
            'Nigeria': {}, 
            'Rwanda': {}, 
            'Senegal': {}, 
            'Sierra Leone': {}, 
            'South Africa': {}, 
            'Sudan': {}, 
            'Tanzania': {}, 
            'Tunisia': {}, 
            'Uganda': {}, 
            'Zambida': {}, 
            'Zimbabwe': {}, 
            'Canary Islands': {}
            }
        },
        'Asia':
        {
            'Subregions': 
            {
            'Afghanistan': {}, 
            'Armenia': {}, 
            'Azerbaijan': {}, 
            'Bahrain': {}, 
            'Bangladesh': {},
            'Bhutan': {}, 
            'Brunei': {}, 
            'Cambodia': {}, 
            'China': {}, 
            'Cyprus': {}, 
            'East Timor (Timor-Leste)': {}, 
            'Egypt': {}, 
            'Georgia': {}, 
            'India': {}, 
            'Indonesia': {}, 
            'Iran': {},
            'Iraq': {}, 
            'Israel': {}, 
            'Japan': {}, 
            'Jordan': {}, 
            'Kazakhstan': {}, 
            'North Korea': {},
            'South Korea': {}, 
            'Kuwait': {}, 
            'Kyrgyzstan': {}, 
            'Laos': {}, 
            'Lebanon': {}, 
            'Malaysia': {}, 
            'Maldives': {}, 
            'Mongolia': {}, 
            'Myanmar': {}, 
            'Nepal': {}, 
            'Oman': {},
            'Pakistan': {}, 
            'Philippines': {}, 
            'Qatar': {}, 
            'Russia': {}, 
            'Saudi Arabia': {},
            'Singapore': {}, 
            'Sri Lanka': {}, 
            'Syria': {}, 
            'Tajikstan': {}, 
            'Thailand': {},
            'Turkey': {}, 
            'Turkmenistan': {}, 
            'United Arab Emirates': {}, 
            'Uzbekistan': {},
            'Vietnam': {}, 
            'Yemen': {}
            }
        },
        'Europe':
        {
            'Subregions': 
            {
            'Albania': {}, 
            'Andorra': {}, 
            'Armenia': {}, 
            'Austria': {}, 
            'Azerbaijan': {},
            'Belarus': {}, 
            'Belgium': {}, 
            'Bosnia and Herzegovina': {}, 
            'Bulgaria': {},
            'Croatia': {}, 
            'Cyprus': {}, 
            'Czech Republic': {}, 
            'Denmark': {}, 
            'Estonia': {},
            'Finland': {}, 
            'France': {}, 
            'Georgia': {}, 
            'Germany': {}, 
            'Greece': {}, 
            'Hungary': {},
            'Iceland': {}, 
            'Ireland': {}, 
            'Italy': {}, 
            'Kazakhstan': {}, 
            'Latvia': {},
            'Liechtenstein': {}, 
            'Lithuania': {}, 
            'Luxembourg': {}, 
            'Malta': {}, 
            'Moldova': {},
            'Monaco': {}, 
            'Montenegro': {}, 
            'Netherlands': {}, 
            'North Macedonia': {}, 
            'Norway': {}, 
            'Poland': {}, 
            'Portugal': {}, 
            'Romania': {}, 
            'Russia': {}, 
            'San Marino': {}, 
            'Serbia': {}, 
            'Slovakia': {}, 
            'Slovenia': {}, 
            'Spain': {}, 
            'Sweden': {}, 
            'Switzerland': {}, 
            'Turkey': {}, 
            'Ukraine': {}, 
            'United Kingdom': {},
            'Vatican City': {}, 
            'Kosovo': {}, 
            'Nothern Cyprus': {}, 
            'Åland': {}, 
            'Faroe Islands': {}, 
            'Gibraltar': {}, 
            'Guernsey': {}, 
            'Isle of Man': {},
            'Jersey': {},
            'Svalbard': {}
            }
        },
        'North America':
        {
            'Subregions': 
            {
            'Antigua and Barbuda': {}, 
            'Bahamas': {}, 
            'Barbados': {}, 
            'Belize': {}, 
            'Canada': {},
            'Costa Rica': {}, 
            'Cuba': {}, 
            'Dominica': {}, 
            'Dominican Republic': {},
            'El Salvador': {}, 
            'Grenada': {}, 
            'Guatemala': {}, 
            'Haiti': {}, 
            'Honduras': {},
            'Jamaica': {}, 
            'Mexico': {}, 
            'Nicaragua': {}, 
            'Panama': {}, 
            'Saint Kitts and Nevis': {}, 
            'Saint Lucia': {}, 
            'Saint Vincent and the Grenadines': {}, 
            'Trinidad and Tobago': {}, 
            'United States':
            {
                'States': 
                [
                    'Alabama', 
                    'Alabama', 
                    'Alaska', 
                    'Arizona', 
                    'Arkansas',
                    'California',
                    'Colorado',
                    'Connecticut',
                    'Delaware',
                    'Florida',
                    'Georgia',
                    'Hawaii',
                    'Idaho',
                    'Illinois',
                    'Indiana',
                    'Iowa',
                    'Kansas',
                    'Kentucky',
                    'Louisiana',
                    'Maine',
                    'Maryland',
                    'Massachusetts',
                    'Michigan',
                    'Minnesota',
                    'Mississippi',
                    'Missouri',
                    'Montana',
                    'Nebraska',
                    'Nevada',
                    'New Hampshire',
                    'New Jersey',
                    'New Mexico',
                    'New York',
                    'North Carolina',
                    'North Dakota',
                    'Ohio',
                    'Oklahoma',
                    'Oregon',
                    'Pennsylvania',
                    'Rhode Island',
                    'South Carolina',
                    'South Dakota',
                    'Tennessee',
                    'Texas',
                    'Utah',
                    'Vermont',
                    'Virginia',
                    'Washington',
                    'Washington, D.C.',
                    'West Virginia',
                    'Wisconsin',
                    'Wyoming',
                    'American Samoa',
                    'Guam',
                    'Northern Mariana Islands',
                    'Puerto Rico',
                    'US Virgin Islands'
                ]
            }, 
            'Anguilla': {}, 
            'Aruba': {},
            'Bermuda': {}, 
            'British Virgin Islands': {}, 
            'Cayman Islands': {}, 
            'Curaçao': {}, 
            'Greenland': {}, 
            'Montserrat': {}, 
            'Puerto Rico': {}, 
            'Turks and Caicos Islands': {}, 
            'United States Virgin Islands': {}
            }
        },
        'Oceania':
        {
            'Subregions': 
            {
            'Australia': {}, 
            'Fiji': {}, 
            'Kiribati': {}, 
            'Nauru': {}, 
            'New Zealand': {}, 
            'Papa New Guinea': {}, 
            'Samoa': {}, 
            'Solomon Islands': {}, 
            'Tonga': {}, 
            'Tuvalu': {},
            'Vanuatu': {}, 
            'Niue': {}, 
            'American Samoa': {}, 
            'Guam': {}, 
            'Hawaii': {}, 
            'Northern Mariana Islands': {}, 
            'Tokelau': {}
            }
        },
        'South America':
        {
            'Subregions': 
            {
            'Argentina': {}, 
            'Bolivia': {}, 
            'Brazil': {}, 
            'Chile': {}, 
            'Colombia': {}, 
            'Ecuador': {},
            'Guyana': {}, 
            'Paraguay': {}, 
            'Peru': {}, 
            'Suriname': {}, 
            'Uruguay': {}, 
            'Venezuela': {},
            'Falkland Islands': {}, 
            'French Guiana': {}, 
            'South Georgia and the South Sandwich Islands': {}
            }
        }
    }
}

with open('validWikiFilters.json', 'w') as file:
    json.dump(valid_filters, file)